# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/your151/文档/Chrono-shift

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/your151/文档/Chrono-shift

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/your151/文档/Chrono-shift/CMakeFiles /home/your151/文档/Chrono-shift//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/your151/文档/Chrono-shift/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chrono-client

# Build rule for target.
chrono-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chrono-client
.PHONY : chrono-client

# fast build rule for target.
chrono-client/fast:
	$(MAKE) $(MAKESILENT) -f client/CMakeFiles/chrono-client.dir/build.make client/CMakeFiles/chrono-client.dir/build
.PHONY : chrono-client/fast

#=============================================================================
# Target rules for targets named chrono-client-gui

# Build rule for target.
chrono-client-gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chrono-client-gui
.PHONY : chrono-client-gui

# fast build rule for target.
chrono-client-gui/fast:
	$(MAKE) $(MAKESILENT) -f client/CMakeFiles/chrono-client-gui.dir/build.make client/CMakeFiles/chrono-client-gui.dir/build
.PHONY : chrono-client-gui/fast

#=============================================================================
# Target rules for targets named gen-certs

# Build rule for target.
gen-certs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen-certs
.PHONY : gen-certs

# fast build rule for target.
gen-certs/fast:
	$(MAKE) $(MAKESILENT) -f client/CMakeFiles/gen-certs.dir/build.make client/CMakeFiles/gen-certs.dir/build
.PHONY : gen-certs/fast

#=============================================================================
# Target rules for targets named gen-certs-force

# Build rule for target.
gen-certs-force: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen-certs-force
.PHONY : gen-certs-force

# fast build rule for target.
gen-certs-force/fast:
	$(MAKE) $(MAKESILENT) -f client/CMakeFiles/gen-certs-force.dir/build.make client/CMakeFiles/gen-certs-force.dir/build
.PHONY : gen-certs-force/fast

#=============================================================================
# Target rules for targets named chrono-client-gui_autogen_timestamp_deps

# Build rule for target.
chrono-client-gui_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chrono-client-gui_autogen_timestamp_deps
.PHONY : chrono-client-gui_autogen_timestamp_deps

# fast build rule for target.
chrono-client-gui_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f client/CMakeFiles/chrono-client-gui_autogen_timestamp_deps.dir/build.make client/CMakeFiles/chrono-client-gui_autogen_timestamp_deps.dir/build
.PHONY : chrono-client-gui_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named chrono-client-gui_autogen

# Build rule for target.
chrono-client-gui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chrono-client-gui_autogen
.PHONY : chrono-client-gui_autogen

# fast build rule for target.
chrono-client-gui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f client/CMakeFiles/chrono-client-gui_autogen.dir/build.make client/CMakeFiles/chrono-client-gui_autogen.dir/build
.PHONY : chrono-client-gui_autogen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chrono-client-gui_autogen"
	@echo "... chrono-client-gui_autogen_timestamp_deps"
	@echo "... gen-certs"
	@echo "... gen-certs-force"
	@echo "... chrono-client"
	@echo "... chrono-client-gui"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

