# Chrono-shift i2pd 配置
log = stdout
loglevel = info
datadir = ./i2p_data

sam.enabled = true
sam.address = 127.0.0.1
sam.port = 7656

httpproxy.enabled = false
socksproxy.enabled = false
bob.enabled = false
i2pcontrol.enabled = false
upnp.enabled = false
nat = false
ipv6 = false
reseed.verify = true
reseed.threshold = 25
